CREATE TABLE IF NOT EXISTS movies
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rating       INTEGER,
    movie        VARCHAR(255),
    release_year INTEGER,    -- экранируем зарезервированное слово YEAR
    country      VARCHAR(255),
    rating_ball  DOUBLE,
    overview     TEXT,
    director     VARCHAR(255),
    screenwriter TEXT ARRAY, -- правильный синтаксис массивов для H2
    actors       TEXT ARRAY,
    url_logo     VARCHAR(255)
);